### ISSUE TITLE
Sporadic Unit Test Failures

### ISSUE THREAD

**Issue by dsm0014** [raft-tech/konfirm#64]
## The Issue
Unit tests, particularly those surrounding finalizers, sporadically fail in github actions. There seems to be no consistency on which K8s version causes failures and little consistency on which test fails (other than they usually have to do with finalizers). Re-running tests _eventually_ will result in success, but we should not have this kind of uncertainty.

## Goal
Determine if there is a root cause for these flaky tests and implement a fix if possible.

**Comment by dagan** [comment]
This seems to have been resolved after updating the setup-go action to V4.
